### PR TITLE
mycoursespage

### PR DESCRIPTION
**Pull request by DonnC**
added device_preview plugin to emulate ui preview on different screensizes
added custom app bar to use out of the box as per design (plug and play)

appbar

added background page with circles as per design (plug and play)
background

added responsive architecture folder
structured utilities files i.e colors, textstyles, themes

coursespage
detailspage
#15 
#5

### CODE REVIEW

**Comment by ignertic** [comment]
The color tho?

**Comment by DonnC** [comment]
I used same colors as in the doc but i dont know why it still gives those, but the good thing is the building block is done ☺ just a fix on color

**Comment by cybertanya** [comment]
This is good bro @DonnC

**Comment by DonnC** [comment]
i added the components that we can reuse rather than recreating them across multiple screens
these are available under widgets folder so that you simply import it and use it

✅ CourseHub AppBar
✅  CourseHub Background
✅  CouseHub small container with circles(bubbles)

**Comment by alistairholmes** [comment]
Nice, thanks for your contribution man

**Review by alistairholmes — COMMENTED** [review]
Great, stuff man, looks good.

**Pull request merged**
